CodingSoldier/CodingSoldier/Controllers/RolesController.cs
using CodingSoldier.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodingSoldier.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        ApplicationDbContext _dbContext;

        public RolesController(IUnityContainer container)
        {
            _dbContext = container.Resolve<DbContext>("ApplicationDbContext") as ApplicationDbContext;
        }

        public ActionResult Index()
        {
            var Roles = _dbContext.Roles.ToList();
            return View(Roles);
        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            var role = new IdentityRole();
            return View(role);
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(IdentityRole role)
        {
            _dbContext.Roles.Add(role);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CodingSoldier/CodingSoldier/Views/Roles/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create Role";
}
 
<h2>Create Role</h2>
 
<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>
 
 
@using (Html.BeginForm())
{
    <table id="tbrole">
        <tr>
            <td>Enter Role Name To be Created:</td>
            <td>
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
    </table><br/>
    <input type="submit" value="Create Role" />
}
<br/>
@Html.ActionLink("Back to Roles List", "index", "roles")

CodingSoldier/CodingSoldier/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2><br/>


<b>Role Name</b>
<ul>
    @foreach (var item in Model)
    {
        <li>
            @item.Name

        </li>
    }
</ul>

@Html.ActionLink("Create Role", "Create", "Roles")