CodingSoldier/CodingSoldier/Models/StudyViewModel.cs
using CodingSoldier.Core.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CodingSoldier.Models
{
    public class StudyViewModel : BaseViewModel
    {
        public int Id { get; set; }
        [Required]
        [AllowHtml]
        public string StudyHeader { get; set; }
        [AllowHtml]
        [Required]
        public string StudyContent { get; set; }
        [Required]
        public string CategoryName { get; set; }     
    }
}

CodingSoldier/CodingSoldier/Controllers/StudiesController.cs
using System.Web.Mvc;
using CodingSoldier.Core.Models;
using CodingSoldier.Core.UnitOfWork;
using CodingSoldier.Models;
using CodingSoldier.Core.Repository;
using System.Linq;
using PagedList;
using AutoMapper;
using System.Collections;
using System.Collections.Generic;
using System;

namespace CodingSoldier.Controllers
{
    public class StudiesController : BaseController<Study, StudyViewModel>
    {
        public StudiesController(IUnitOfWork uow) :
            base(uow)
        {

        }

        public override ActionResult Index(int page = 1, int pageSize = 2, string studyHeader = null)
        {
            if (studyHeader != null)
            {
                var model = _modelRepository.GetAll().Where(m => m.StudyHeader == studyHeader);
                var viewModel = Mapper.Map<IEnumerable<StudyViewModel>>(model);
                return View(viewModel);
            }
            else
            {
                return base.Index(page, pageSize);
            }      
        }

        public override ActionResult Search(string title)
        {
            ViewBag.SearchText = title;
            var studies = _modelRepository as IRepository<Study>;
            var searchedStudies = studies.GetAll().Where(s => s.StudyHeader.Contains(title) || s.StudyContent.Contains(title));
            var viewModel = Mapper.Map<List<StudyViewModel>>(searchedStudies);            
            return View(viewModel);
        }
    }
}

CodingSoldier/CodingSoldier/Views/Studies/Create.cshtml
@model CodingSoldier.Models.StudyViewModel

@{
    ViewBag.Title = "Create Study";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Study</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.StudyHeader, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StudyHeader, new { @class = "textBoxHeader" })
                @Html.ValidationMessageFor(model => model.StudyHeader)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudyContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.StudyContent, new { @class = "textAreaContent" })
                @Html.ValidationMessageFor(model => model.StudyContent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryName, Model.Categories, new { @class = "verticalAlignBaseLine" })
                @Html.ValidationMessageFor(model => model.CategoryName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CodingSoldier/CodingSoldier/Views/Studies/Edit.cshtml
@model CodingSoldier.Models.StudyViewModel

@{
    ViewBag.Title = "Edit Study";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Study</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StudyHeader, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StudyHeader, new { @class = "textBoxHeader" })
                @Html.ValidationMessageFor(model => model.StudyHeader)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudyContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.StudyContent, new { @class = "textAreaContent" })
                @Html.ValidationMessageFor(model => model.StudyContent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryName, Model.Categories, new { @class = "verticalAlignBaseLine" })                
                @Html.ValidationMessageFor(model => model.CategoryName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CodingSoldier/CodingSoldier/Views/Studies/Index.cshtml
@model IEnumerable<CodingSoldier.Models.StudyViewModel>

@{
    ViewBag.Title = "Studies - Boney Johns";
    var model = Model as IPagedList<CodingSoldier.Models.StudyViewModel>;
 }

<h3>Studies</h3>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

@if (model != null)
{
    <div style="float:right">
        @using (Html.BeginForm("Search", "Studies", FormMethod.Post))
        {
            @Html.TextBox("title", "", new { placeholder = "enter the search text!" })
            <input type="submit" title="Search" value="Search" />
        }
    </div>
}


@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-4">
            <b>@Html.Raw(item.StudyHeader)</b>
            @if (User.IsInRole("Admin"))
            {
                <text>(</text>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <text>|</text>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { onclick = "return confirm('Are you sure you wish to delete this study?');" })
                <text>)</text>
            }
            <br />
            <i>Category: @item.CategoryName</i>
        </div>        
    </div>
    <div class="row">
        <div class="col-md-4 col-lg-12 col-sm-2">
            <pre>@Html.Raw(item.StudyContent)</pre>
        </div>
    </div>
    <div class="row" style="margin-top:5px">
    </div>
}


@if (model != null)
{
    <div id='Paging' style="text-align:center">
        Page @(model.PageCount < model.PageNumber ? 0 : model.PageNumber) of @(model.PageCount)

        @Html.PagedListPager(model, page => Url.Action("Index", new { page }))
    </div>
}

CodingSoldier/CodingSoldier/Views/Studies/Search.cshtml
@model IEnumerable<CodingSoldier.Models.StudyViewModel>

@{
    ViewBag.Title = "Studies - Search";
}

<div>
    <b>Search Results for:</b> "@ViewBag.SearchText"
</div>
<br/>

<div>
    @if (Model.Any())
    {
        <ol>
            @foreach (var item in Model)
            {
                <li>@Html.ActionLink(item.StudyHeader, "Index", new { studyHeader = item.StudyHeader })</li>
            }
        </ol>
    }
    else
    {
        <p>No results found!</p>
    }

</div>